manifest_version = "3.0"
name = "openrouter-chatbot"
description = "OpenRouter Chatbot with Next.js"
authors = ["Your Name"]
language = "javascript"
service_id = "zxnYvwtkGA0LcGWV2SMOw4"

[scripts]
  build = "pnpm run build && pnpm run fastly:build"

[setup]
  [setup.env]
    OPENROUTER_API_KEY = ""

[build]
  [build.env]
    NODE_ENV = "production"

[local_server]
  [local_server.backends]
    [local_server.backends.origin]
      url = "http://localhost:3000"